// The purpose of this file is to fix up the rich text so it can be formatted properly

String fixRichText(String text) {
// add <p> to the beginning of the text and </p> to the end of the text if they don't exist
  text = '<pre>' + text + '</pre>';

  return text
      .replaceAll("<br>", "\n")
      .replaceAll("<i>", "*")
      .replaceAll("</i>", "*")
      .replaceAll("<b>", "**")
      .replaceAll("</b>", "**")
      .replaceAll("<p>", "\n\n")
      .replaceAll("</p>", "")
      .replaceAll("<u>", "__")
      .replaceAll("</u>", "__")
      .replaceAll("<strong>", "**")
      .replaceAll("</strong>", "**")
      .replaceAll("<em>", "*")
      .replaceAll("</em>", "*")
      .replaceAll("<a>", "")
      .replaceAll("</a>", "")
      .replaceAll("<ul>", " * ")
      .replaceAll("</ul>", "")
      .replaceAll("<li>", " * ")
      .replaceAll("</li>", "")
      .replaceAll("<ol>", " 1. ")
      .replaceAll("</ol>", "")
      .replaceAll("<div>", "")
      .replaceAll("</div>", "")
      .replaceAll("<span>", "")
      .replaceAll("</span>", "")
      .replaceAll("<h1>", "")
      .replaceAll("</h1>", "")
      .replaceAll("<h2>", "")
      .replaceAll("</h2>", "")
      .replaceAll("<h3>", "")
      .replaceAll("</h3>", "")
      .replaceAll("<h4>", "")
      .replaceAll("</h4>", "")
      .replaceAll("<h5>", "")
      .replaceAll("</h5>", "")
      .replaceAll("<h6>", "")
      .replaceAll("</h6>", "")
      .replaceAll("<hr>", "")
      .replaceAll("</hr>", "")
      .replaceAll("<blockquote>", "> ")
      .replaceAll("</blockquote>", "")
      .replaceAll("<pre>", "")
      .replaceAll("</pre>", "")
      .replaceAll("<code>", "`")
      .replaceAll("</code>", "`")
      .replaceAll("<sup>", "^(")
      .replaceAll("</sup>", ")")
      .replaceAll("<sub>", "_(")
      .replaceAll("</sub>", ")");
}
