allprojects {
    repositories {
        google()
        mavenCentral()
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

def rootBuildDir = rootProject.layout.buildDirectory.get().dir('../../build')
rootProject.layout.buildDirectory.value(rootBuildDir)
subprojects {
    def subProjectBuildDir = rootBuildDir.dir(project.name)
    project.layout.buildDirectory.value(subProjectBuildDir)
}
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion flutter.compileSdkVersion
                buildToolsVersion "37.0.0"
            }
        }
    }
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
